version: 2

defaults: &defaults
  context: org-global

workflows:
  version: 2
  build:
    jobs:
      - build:
          <<: *defaults
    triggers:
      - schedule:
          cron: "0 22 * * 3" # Wed 22:00 UTC
          filters:
            branches:
              only:
                - master

jobs:
  build:
    docker:
      - image: alpine:3.9
    steps:
      - checkout
      - run:
          name: Init
          command: |
            apk add --no-cache bash curl ca-certificates make jq
            curl -sSL https://github.com/previousnext/notify/releases/download/2.1.0/notify_linux_amd64 -o /usr/local/bin/notify && \
              chmod +rx /usr/local/bin/notify
      - run:
          name: Post issues
          command: |
            DAYS_AGO=28
            VERSION=8.8.x-dev
            URLS=$(./rtbc-outdated.sh)
            if [[ ! -z $URLS ]] && notify --channel="#sys-ops-builds" --username="Drupal.org" --icon-emoji=":drupal8:" --message="The following RTBC issues have not been updated in $DAYS_AGO days: \n $URLS"
